// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU3QFzAKFMNzWVo4Md_71-xIruEwYP3dA',
    appId: '1:1083861624380:web:779d6d10895c732c71c539',
    messagingSenderId: '1083861624380',
    projectId: 'schoolevents-341fc',
    authDomain: 'schoolevents-341fc.firebaseapp.com',
    storageBucket: 'schoolevents-341fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD97_kKbjGGKbDXCc2QP87DTFZuMLDWSgE',
    appId: '1:1083861624380:android:2cba51b88b19bd2271c539',
    messagingSenderId: '1083861624380',
    projectId: 'schoolevents-341fc',
    storageBucket: 'schoolevents-341fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_s2tSd8-D3QP7EN-4fClo-7iIBtyQuOk',
    appId: '1:1083861624380:ios:88473f47c8d72ebe71c539',
    messagingSenderId: '1083861624380',
    projectId: 'schoolevents-341fc',
    storageBucket: 'schoolevents-341fc.firebasestorage.app',
    iosBundleId: 'com.example.schoolevents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_s2tSd8-D3QP7EN-4fClo-7iIBtyQuOk',
    appId: '1:1083861624380:ios:88473f47c8d72ebe71c539',
    messagingSenderId: '1083861624380',
    projectId: 'schoolevents-341fc',
    storageBucket: 'schoolevents-341fc.firebasestorage.app',
    iosBundleId: 'com.example.schoolevents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU3QFzAKFMNzWVo4Md_71-xIruEwYP3dA',
    appId: '1:1083861624380:web:b296831801145c0571c539',
    messagingSenderId: '1083861624380',
    projectId: 'schoolevents-341fc',
    authDomain: 'schoolevents-341fc.firebaseapp.com',
    storageBucket: 'schoolevents-341fc.firebasestorage.app',
  );
}
